export const exampleRepositories = [
  {
    id: 123456789,
    name: "react-dashboard",
    full_name: "yourusername/react-dashboard",
    description: "A modern dashboard built with React, TypeScript, and Tailwind CSS",
    private: false,
    html_url: "https://github.com/yourusername/react-dashboard",
    stargazers_count: 342,
    watchers_count: 342,
    forks_count: 45,
    language: "TypeScript",
    updated_at: "2025-10-15T14:30:00Z",
    visibility: "public",
  },
  {
    id: 234567890,
    name: "node-api-boilerplate",
    full_name: "yourusername/node-api-boilerplate",
    description: "Production-ready Node.js REST API with authentication and PostgreSQL",
    private: false,
    html_url: "https://github.com/yourusername/node-api-boilerplate",
    stargazers_count: 1205,
    watchers_count: 1205,
    forks_count: 178,
    language: "JavaScript",
    updated_at: "2025-10-10T09:15:00Z",
    visibility: "public",
  },
  {
    id: 345678901,
    name: "web-scraper-toolkit",
    full_name: "yourusername/web-scraper-toolkit",
    description: "Powerful web scraping utilities with Puppeteer and Cheerio",
    private: true,
    html_url: "https://github.com/yourusername/web-scraper-toolkit",
    stargazers_count: 89,
    watchers_count: 89,
    forks_count: 12,
    language: "JavaScript",
    updated_at: "2025-10-16T18:45:00Z",
    visibility: "private",
  },
  {
    id: 456789012,
    name: "rust-cli-tools",
    full_name: "yourusername/rust-cli-tools",
    description: "Collection of command-line utilities written in Rust",
    private: false,
    html_url: "https://github.com/yourusername/rust-cli-tools",
    stargazers_count: 567,
    watchers_count: 567,
    forks_count: 34,
    language: "Rust",
    updated_at: "2025-10-12T11:20:00Z",
    visibility: "public",
  },
  {
    id: 567890123,
    name: "docker-compose-collection",
    full_name: "yourusername/docker-compose-collection",
    description: "Ready-to-use Docker Compose configurations for common development stacks",
    private: false,
    html_url: "https://github.com/yourusername/docker-compose-collection",
    stargazers_count: 2341,
    watchers_count: 2341,
    forks_count: 423,
    language: "Shell",
    updated_at: "2025-10-14T16:00:00Z",
    visibility: "public",
  },
  {
    id: 678901234,
    name: "realtime-chat-app",
    full_name: "yourusername/realtime-chat-app",
    description: "WebSocket-based chat application with React and Socket.io",
    private: false,
    html_url: "https://github.com/yourusername/realtime-chat-app",
    stargazers_count: 156,
    watchers_count: 156,
    forks_count: 28,
    language: "TypeScript",
    updated_at: "2025-10-08T13:30:00Z",
    visibility: "public",
  },
  {
    id: 789012345,
    name: "pdf-processing-service",
    full_name: "yourusername/pdf-processing-service",
    description: "Microservice for PDF generation and manipulation",
    private: true,
    html_url: "https://github.com/yourusername/pdf-processing-service",
    stargazers_count: 23,
    watchers_count: 23,
    forks_count: 3,
    language: "JavaScript",
    updated_at: "2025-10-13T10:00:00Z",
    visibility: "private",
  },
  {
    id: 890123456,
    name: "awesome-resources",
    full_name: "yourusername/awesome-resources",
    description: null,
    private: false,
    html_url: "https://github.com/yourusername/awesome-resources",
    stargazers_count: 789,
    watchers_count: 789,
    forks_count: 91,
    language: null,
    updated_at: "2025-09-28T08:15:00Z",
    visibility: "public",
  },
  {
    id: 901234567,
    name: "graphql-server",
    full_name: "yourusername/graphql-server",
    description: "GraphQL API server with Apollo and Express",
    private: false,
    html_url: "https://github.com/yourusername/graphql-server",
    stargazers_count: 445,
    watchers_count: 445,
    forks_count: 67,
    language: "TypeScript",
    updated_at: "2025-10-11T15:45:00Z",
    visibility: "public",
  },
  {
    id: 1012345678,
    name: "e-commerce-platform",
    full_name: "yourusername/e-commerce-platform",
    description: "Full-stack e-commerce solution with Next.js and Stripe integration",
    private: true,
    html_url: "https://github.com/yourusername/e-commerce-platform",
    stargazers_count: 12,
    watchers_count: 12,
    forks_count: 1,
    language: "TypeScript",
    updated_at: "2025-10-17T07:30:00Z",
    visibility: "private",
  },
]
